cache:
  directories:
    - vendor

language: php

php:
  - 7.0
  - hhvm

addons:
  mariadb: 10.1

before_script:
  - mysql -e 'create database osudb;'

env:
  - DB_USERNAME=root

matrix:
  fast_finish: true

install:
  - ./build.sh